### ISSUE TITLE
Keyboard Nav: Arrows

### ISSUE THREAD

**Issue by mbutterworth** [jgarber623/aria-collapsible#3]
I like what you're doing here, but have a concern.

Wouldn't one expect to tab to the Menu button and then use up & down arrows to traverse the list?

**Comment by jgarber623** [comment]
Thanks for the feedback, Matt!

I wouldn't immediately expect the arrow keys to behave that way for a couple of reasons:
1. Default arrow key behavior in browsers scroll the viewport up/down.
2. Navigating between focusable elements on a page is the tab key's default behavior.
3. I _believe_ that adding the up/down arrow key behavior you describe implies a vertically-oriented list of navigation items. Would the up/down arrow key behavior make sense with a horizontal navigation list? Further, aria-collapsible is useful for more than the show/hide navigation behavior in the example.

What do you think? (Let me know, too, if I've misinterpreted your concern.)

Also, I'd be curious what @ten1seven might have to say about the described behavior.

**Comment by ten1seven** [comment]
If this was a [tabbed interface](http://heydonworks.com/practical_aria_examples/#tab-interface), using the left/right arrow keys is an appropriate and recommended pattern for moving between tabs. However, aria-collapsible is a simple 1:1 toggler where the buttons aren't meant to be connected into a tabbed interface.

Maybe an opportunity for an aria-tabs script @jgarber623?

**Comment by jgarber623** [comment]
@ten1seven 

![](http://gifrific.com/wp-content/uploads/2012/12/John-Cena-Not-Bad.gif)
